pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('mle-lab-docker')
        LC_ALL = "ru_RU.UTF-8"
        LANG    = "ru_RU.UTF-8"
        LANGUAGE = "ru_RU.UTF-8"
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
	}

    stages {

        stage('Clone github repository') {
            steps {
                cleanWs()
                bat 'chcp 65001 && git clone -b main https://github.com/jenyanorilsk/mle_1_homework.git'
            }
        }

        stage('Checkout repo dir') {
            steps {
                bat encoding: 'UTF-8', script: 'cd mle_1_homework && dir'
            }
        }

        //stage('Login'){
        //    steps {
        //        bat 'chcp 65001 && winpty docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
        //    }
        //}

        //stage('debug-creds-output'){
        //    steps {
        //        bat 'chcp 65001 && echo %DOCKERHUB_CREDS_USR% && echo %DOCKERHUB_CREDS_PSW%'
        //    }
        //}

        
        //stage('Create and run docker container') {
        //    steps {
        //        script {
        //            try {
        //                bat 'chcp 65001 && cd mle_1_homework && docker-compose build'
        //            }
        //            finally {
        //                bat '''
        //                    chcp 65001
        //                    cd mle_1_homework
        //                    docker-compose up -d
        //                    '''
        //            }
        //        }
        //    }
        //}

        //stage('Checkout container logs') {
        //    steps {

        //        bat '''echo "DEBUG PROCESSES:" && docker ps'''

        //        dir("mle_1_homework") {
        //                bat '''
        //                    docker-compose up -d
        //                    for /f %%i in ('docker ps -qf "name=^mle_1_homework_web_1"') do set containerId=%%i
        //                    echo %containerId%
        //                    IF "%containerId%" == "" (
        //                        echo "No container running"
        //                    )
        //                    ELSE (
        //                        docker logs --tail 1000 -f %containerId%
        //                        )
        //                '''
        //            }
        //    }
        //}

        //stage('Checkout coverage report'){
        //    steps{
        //        dir("mle_1_homework"){
        //            bat '''
        //            docker-compose logs -t --tail 10
        //            '''
        //        }
        //    }
        //}

        //stage('Push'){
        //    steps{
        //        bat 'chcp 65001 && docker push jenyanorilsk/mle_lab:latest'
        //    }
        //}

    }

    post {
        always {
            bat 'chcp 65001 && docker logout'
        }
    }

}